In [1]:
import numpy as np

### Q1. Create a 3×3 numpy array of all True’s

In [61]:
x = np.ones((3,3), dtype=bool)
x

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

### Q2. Extract all odd numbers from arr
Input:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2==1]

array([1, 3, 5, 7, 9])

### Q3. Replace all odd numbers in arr with -1
Input:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
np.where((arr%2==1),-1,arr)

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

### Q4. Stack arrays a and b vertically
Input
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [73]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### Q5. Stack the arrays a and b horizontally.
Input
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [74]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.hstack((a,b))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

### Q6. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
Input:
a = np.array([1,2,3])
```Desired Output:
array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])```

In [97]:
a = np.array([1,2,3])
np.r_[np.repeat(a,3), np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

### Q7. Get the common items between a and b
Input:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```Desired Output:
array([2, 4])```

In [85]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

### Q8. From array a remove all items present in array b
Input:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
```Desired Output:
array([1,2,3,4])```

In [91]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

### Q9. Get the positions where elements of a and b match
Input:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```Desired Output:
(array([1, 3, 5, 7]),)```

In [92]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

### Q10. Get all items between 5 and 10 from a.
Input:
a = np.array([2, 6, 1, 9, 10, 3, 27])
```Desired Output:
array([6, 9, 10])```

In [94]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
a[(a>5)&(a<11)]

array([ 6,  9, 10])

### Q11. Swap columns 1 and 2 in the array arr.
arr = np.arange(9).reshape(3,3)

In [96]:
arr = np.arange(9).reshape(3,3)
arr[:,[0,2,1]]

array([[0, 2, 1],
       [3, 5, 4],
       [6, 8, 7]])

### Q12. Reverse the rows of a 2D array arr.
Input:
arr = np.arange(9).reshape(3,3)

In [98]:
arr = np.arange(9).reshape(3,3)
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

### Q13. Reverse the columns of a 2D array arr.
Input:
arr = np.arange(9).reshape(3,3)

In [102]:
arr = np.arange(9).reshape(3,3)
arr[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

### Q14. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.

In [106]:
arr = np.random.uniform(5,10,size=(5,3))
arr

array([[6.5358986 , 5.24562223, 9.67359587],
       [9.54985969, 9.61728467, 8.62829783],
       [8.69124695, 7.10766619, 5.73870346],
       [7.59181383, 7.4705529 , 9.97355004],
       [8.93266368, 7.27967146, 8.72188078]])

### Q15. Print or show only 3 decimal places of the numpy array rand_arr.
Input:
rand_arr = np.random.random((5,3))

In [116]:
rand_arr = np.round(np.random.random((5,3)),3)
rand_arr

array([[0.33 , 0.998, 0.292],
       [0.69 , 0.734, 0.304],
       [0.835, 0.679, 0.055],
       [0.101, 0.12 , 0.383],
       [0.952, 0.124, 0.867]])

### Q16. Limit the number of items printed in python numpy array a to a maximum of 6 elements.
Input:
a = np.arange(15)
```Desired Output:
array([ 0,  1,  2, ..., 12, 13, 14])```

In [118]:
np.set_printoptions(threshold=6)
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14])

### Q17. Print the full numpy array a without truncating.
Input:
np.set_printoptions(threshold=6)
a = np.arange(15)
```Desired Output:
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])```

In [100]:
np.set_printoptions(threshold=6)
a = np.arange(15)
np.set_printoptions(threshold=np.inf)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### Q18. From the array a, replace all values greater than 30 to 30 and less than 10 to 10.
Input:
np.random.seed(100)
a = np.random.uniform(1,50, 20)

In [101]:
np.random.seed(100)
a = np.random.uniform(1,50, 20)
np.clip(a, a_min=10, a_max=30)

array([27.62684215, 14.64009987, 21.80136195, 30.        , 10.        ,
       10.        , 30.        , 30.        , 10.        , 29.17957314,
       30.        , 11.25090398, 10.08108276, 10.        , 11.76517714,
       30.        , 30.        , 10.        , 30.        , 14.42961361])

### Q19. Get the positions of top 5 maximum values in a given array a.
np.random.seed(100)
a = np.random.uniform(1,50, 20)

In [105]:
np.random.seed(100)
a = np.random.uniform(1,50, 20)
position = np.argsort(a)[-5:]
sorted_arr = a[np.argsort(a)]
values = sorted_arr[-5:]
print(position)
print(values)

[18  7  3 10 15]
[40.99501269 41.466785   42.39403048 44.67477576 48.95256545]


# *Need to fix
### Q20. Convert array_of_arrays into a flat linear 1d array.
Input:
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

array_of_arrays = np.array([arr1, arr2, arr3])
```Desired Output:
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])```

In [108]:
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)
arr_of_arrays = np.array([arr1, arr2, arr3], dtype=object)
np.concatenate(arr_of_arrays)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Q21. Compute the one-hot encodings (dummy binary variables for each unique value in the array)
Input:
np.random.seed(101) 
arr = np.random.randint(1,4, size=6)
```Output:
array([[ 0.,  1.,  0.],
        [ 0.,  0.,  1.],
        [ 0.,  1.,  0.],
        [ 0.,  1.,  0.],
        [ 0.,  1.,  0.],
        [ 1.,  0.,  0.]])```

In [144]:
np.random.seed(101)
def binary_converter(x):
    uniqs = np.unique(x)
    binary = np.zeros((x.shape[0], uniqs.shape[0]))
    for i, k in enumerate(x):
        binary[i, k-1] = 1
    return binary

arr = np.random.randint(1,4, size=6)
binary_converter(arr)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

### Q22. Create the ranks for the given numeric array a.
Input:
np.random.seed(10)
a = np.random.randint(20, size=10)
```Desired output:
[4 2 6 0 8 7 9 3 5 1]```

In [110]:
np.random.seed(10)
a = np.random.randint(20, size=10)
np.argsort(a).argsort()

array([4, 2, 6, 0, 8, 7, 9, 3, 5, 1], dtype=int64)

### Q23. Create a rank array of the same shape as a given numeric array a.
Input:
np.random.seed(10)
a = np.random.randint(20, size=[2,5])
```Desired output:
 [[4 2 6 0 8]
  [7 9 3 5 1]]```

In [116]:
np.random.seed(10)
a = np.random.randint(20, size=[2,5])
np.ravel(a).argsort().argsort().reshape(a.shape)

array([[4, 2, 6, 0, 8],
       [7, 9, 3, 5, 1]], dtype=int64)

### Q24. Compute the maximum for each row in the given array.
np.random.seed(100)
a = np.random.randint(1,10, [5,3])

In [117]:
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
np.amax(a, axis=1)

array([9, 8, 6, 3, 9])

### Q25. Compute the min-by-max for each row for given 2d numpy array.
np.random.seed(100)
a = np.random.randint(1,10, [5,3])

In [45]:
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
np.apply_along_axis(lambda x: np.min(x)/np.max(x), arr=a, axis=1)

array([0.44444444, 0.125     , 0.5       , 1.        , 0.11111111])

### Q26. Find the duplicate entries (2nd occurrence onwards) in the given numpy array and mark them as True. First time occurrences should be False.
Input:
np.random.seed(100)
a = np.random.randint(0, 5, 10)
```Desired Output:
[False  True False  True False False  True  True  True  True]```

In [124]:
np.random.seed(100)
a = np.random.randint(0, 5, 10)
# array of all True
output = np.full(a.shape[0], True)
# index positions of first unique elements 
uniq_positions = np.unique(a, return_index=True)[1]
# make first unique elements to False in output array
output[uniq_positions]=False
output

array([False,  True, False,  True, False, False,  True,  True,  True,
        True])

### Q27. Drop all nan values from a 1D numpy array
Input:
np.array([1,2,3,np.nan,5,6,7,np.nan])
```Desired Output:
array([ 1.,  2.,  3.,  5.,  6.,  7.])```

In [12]:
x = np.array([1,2,3,np.nan,5,6,7,np.nan])
x = x[~np.isnan(x)]
x

array([1., 2., 3., 5., 6., 7.])

### Q28. Compute the euclidean distance between two arrays a and b.
Input:
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])

In [13]:
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])
np.linalg.norm(a-b)

6.708203932499369

### Q29. Find all the peaks in a 1D numpy array a. Peaks are points surrounded by smaller values on both sides.
Input:
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])
```Desired Output:
array([2, 5])```
where, 2 and 5 are the positions of peak values 7 and 6.

In [131]:
# doublediff = np.diff(np.sign(np.diff(a)))
# peak_locations = np.where(doublediff == -2)[0] + 1
# peak_locations
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])
double_diff = np.diff(np.sign(np.diff(a)))
peaks = np.where(double_diff==-2)[0] + 1
peaks

array([2, 5], dtype=int64)

### Q30. Find the index of 5th repetition of number 1 in x.
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])

In [141]:
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
np.argsort(x)[4]

8

### Q31. Convert numpy's datetime64 object to datetime's datetime object
#### Input: a numpy datetime64 object
dt64 = np.datetime64('2018-02-25 22:10:10')

In [7]:
from datetime import datetime
dt64 = np.datetime64('2018-02-25 22:10:10')
dt64.astype(datetime)

datetime.datetime(2018, 2, 25, 22, 10, 10)

### Q32. Compute the moving average of window size 3, for the given 1D array.
Input:
np.random.seed(100)
Z = np.random.randint(10, size=10)

In [147]:
np.random.seed(100)
Z = np.random.randint(10, size=10)
np.convolve(Z, np.ones(3)/3, mode='valid').round(2)   # round() to specify numbers after decimal

array([6.33, 6.  , 5.67, 4.67, 3.67, 2.  , 3.67, 3.  ])

### Q33. Create a numpy array of length 10, starting from 5 and has a step of 3 between consecutive numbers

In [18]:
x = np.arange(5,33,3)
x

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32])

### Q34. Given an array of a non-continuous sequence of dates. Make it a continuous sequence of dates, by filling in the missing dates.
Input:
dates = np.arange(np.datetime64('2018-02-01'), np.datetime64('2018-02-25'), 2)

In [161]:
dates = np.arange(np.datetime64('2018-02-01'), np.datetime64('2018-02-25'), 2)
dates2 = np.array([np.arange(date, (date+d)) for date, d in zip(dates, np.diff(dates))]).reshape(-1)
seq = np.hstack([dates2,dates[-1]])
seq

array(['2018-02-01', '2018-02-02', '2018-02-03', '2018-02-04',
       '2018-02-05', '2018-02-06', '2018-02-07', '2018-02-08',
       '2018-02-09', '2018-02-10', '2018-02-11', '2018-02-12',
       '2018-02-13', '2018-02-14', '2018-02-15', '2018-02-16',
       '2018-02-17', '2018-02-18', '2018-02-19', '2018-02-20',
       '2018-02-21', '2018-02-22', '2018-02-23'], dtype='datetime64[D]')

### Q35. Import the iris dataset keeping the text intact.
Since we want to retain the species, a text field, set the dtype to object. Had it been set dtype=None, a 1d array of tuples would have been returned.

In [163]:
iris_1d = np.genfromtxt('iris.data', delimiter=',', dtype='object')
iris_1d[:5]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa'],
       [b'5.0', b'3.6', b'1.4', b'0.2', b'Iris-setosa']], dtype=object)

### Q36. Extract the text column species from the 1D iris imported in previous question.
Input:
iris_1d = np.genfromtxt('iris.data', delimiter=',', dtype=None)

In [196]:
iris_1d = np.genfromtxt('iris.data', delimiter=',', dtype=None, encoding='utf-8')
species = np.array([row[4] for row in iris_1d])
species[:5]

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa'], dtype='<U15')

### Q37. Convert the 1D iris to 2D array iris_2d by omitting the species text field.
Input:
iris_1d = np.genfromtxt('iris.data', delimiter=',', dtype=None)

In [173]:
iris_2d = np.genfromtxt('iris.data', delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

### Q38. Find the mean, median, standard deviation of iris's sepallength (1st column)
Input:
iris = np.genfromtxt('iris.data', delimiter=',', dtype='object')

In [30]:
iris = np.genfromtxt('iris.data', delimiter=',', dtype=None, usecols=[0])
mn = np.mean(iris)
md = np.median(iris)
sd = np.std(iris)
print(f'iris-mean: {mn}\niris-median: {md}\niris-standard deviation: {sd}')

iris-mean: 5.843333333333334
iris-median: 5.8
iris-standard deviation: 0.8253012917851409


### Q39. Create a normalized form of iris's sepallength whose values range exactly between 0 and 1 so that the minimum has value 0 and maximum has value 1.
Input:
sepallength = np.genfromtxt('iris.data', delimiter=',', dtype='float', usecols=[0])

In [202]:
sepallength = np.genfromtxt('iris.data', delimiter=',', dtype='float', usecols=[0])
smin = sepallength.min()
smax = sepallength.max()
s_normalize = (sepallength-smin)/(smax-smin)
s_normalize.round(3)

array([0.222, 0.167, 0.111, 0.083, 0.194, 0.306, 0.083, 0.194, 0.028,
       0.167, 0.306, 0.139, 0.139, 0.   , 0.417, 0.389, 0.306, 0.222,
       0.389, 0.222, 0.306, 0.222, 0.083, 0.222, 0.139, 0.194, 0.194,
       0.25 , 0.25 , 0.111, 0.139, 0.306, 0.25 , 0.333, 0.167, 0.194,
       0.333, 0.167, 0.028, 0.222, 0.194, 0.056, 0.028, 0.194, 0.222,
       0.139, 0.222, 0.083, 0.278, 0.194, 0.75 , 0.583, 0.722, 0.333,
       0.611, 0.389, 0.556, 0.167, 0.639, 0.25 , 0.194, 0.444, 0.472,
       0.5  , 0.361, 0.667, 0.361, 0.417, 0.528, 0.361, 0.444, 0.5  ,
       0.556, 0.5  , 0.583, 0.639, 0.694, 0.667, 0.472, 0.389, 0.333,
       0.333, 0.417, 0.472, 0.306, 0.472, 0.667, 0.556, 0.361, 0.333,
       0.333, 0.5  , 0.417, 0.194, 0.361, 0.389, 0.389, 0.528, 0.222,
       0.389, 0.556, 0.417, 0.778, 0.556, 0.611, 0.917, 0.167, 0.833,
       0.667, 0.806, 0.611, 0.583, 0.694, 0.389, 0.417, 0.583, 0.611,
       0.944, 0.944, 0.472, 0.722, 0.361, 0.944, 0.556, 0.667, 0.806,
       0.528, 0.5  ,

### Q40. Compute the softmax score of sepallength.
Input:
sepallength = np.genfromtxt('iris.data', delimiter=',', dtype='float', usecols=[0])

In [204]:
def softmax(x):
    # compute softmax values for each sets of scores in x
    return np.exp(x) / np.sum(np.exp(x), axis=0)

sepallength = np.genfromtxt('iris.data', delimiter=',', dtype='float', usecols=[0])
softmax(sepallength).round(3)

array([0.002, 0.002, 0.001, 0.001, 0.002, 0.003, 0.001, 0.002, 0.001,
       0.002, 0.003, 0.002, 0.002, 0.001, 0.004, 0.004, 0.003, 0.002,
       0.004, 0.002, 0.003, 0.002, 0.001, 0.002, 0.002, 0.002, 0.002,
       0.002, 0.002, 0.001, 0.002, 0.003, 0.002, 0.003, 0.002, 0.002,
       0.003, 0.002, 0.001, 0.002, 0.002, 0.001, 0.001, 0.002, 0.002,
       0.002, 0.002, 0.001, 0.003, 0.002, 0.015, 0.008, 0.013, 0.003,
       0.009, 0.004, 0.007, 0.002, 0.01 , 0.002, 0.002, 0.005, 0.005,
       0.006, 0.004, 0.011, 0.004, 0.004, 0.007, 0.004, 0.005, 0.006,
       0.007, 0.006, 0.008, 0.01 , 0.012, 0.011, 0.005, 0.004, 0.003,
       0.003, 0.004, 0.005, 0.003, 0.005, 0.011, 0.007, 0.004, 0.003,
       0.003, 0.006, 0.004, 0.002, 0.004, 0.004, 0.004, 0.007, 0.002,
       0.004, 0.007, 0.004, 0.016, 0.007, 0.009, 0.027, 0.002, 0.02 ,
       0.011, 0.018, 0.009, 0.008, 0.012, 0.004, 0.004, 0.008, 0.009,
       0.03 , 0.03 , 0.005, 0.013, 0.004, 0.03 , 0.007, 0.011, 0.018,
       0.007, 0.006,

### Q41. Find the 5th and 95th percentile of iris's sepallength
Input:
sepallength = np.genfromtxt('iris.data', delimiter=',', dtype='float', usecols=[0])

In [205]:
sepallength = np.genfromtxt('iris.data', delimiter=',', dtype='float', usecols=[0])
np.percentile(sepallength, q=[5,95])

array([4.6  , 7.255])

### Q42. Insert np.nan values at 20 random positions in iris_2d dataset
Input:
iris_2d = np.genfromtxt('iris.data', delimiter=',', dtype='object')

In [209]:
np.random.seed(100)
iris_2d = np.genfromtxt('iris.data', delimiter=',', dtype='object')
iris_2d.ravel()[np.random.choice(iris_2d.size, 20, replace=False)] = np.nan
iris_2d[:10]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.6', b'3.1', b'1.5', b'0.2', nan],
       [b'5.0', b'3.6', b'1.4', b'0.2', b'Iris-setosa'],
       [b'5.4', b'3.9', b'1.7', b'0.4', b'Iris-setosa'],
       [b'4.6', b'3.4', b'1.4', b'0.3', b'Iris-setosa'],
       [b'5.0', b'3.4', b'1.5', b'0.2', b'Iris-setosa'],
       [b'4.4', b'2.9', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.1', b'1.5', nan, b'Iris-setosa']], dtype=object)

### Q43. Find the number and position of missing values in iris_2d's sepallength (1st column)
Input:
iris_2d = np.genfromtxt('iris.data', delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

In [239]:
np.random.seed(100)
iris_2d = np.genfromtxt('iris.data', delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
numbers = np.isnan(iris_2d[:,0]).sum()
positions = np.where(np.isnan(iris_2d[:,0]))
print(f'Number: {numbers}\nPosition: {position}')

Number: 4
Position: [18  7  3 10 15]


### Q44. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0
Input:
iris_2d = np.genfromtxt('iris.data', delimiter=',', dtype='float', usecols=[0,1,2,3])

In [240]:
iris_2d = np.genfromtxt('iris.data', delimiter=',', dtype='float', usecols=[0,1,2,3])
mask = (iris_2d[:,2]>1.5) & (iris_2d[:,0]<5.0)
iris_2d[mask]

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

### Q45. Select the rows of iris_2d that does not have any nan value.
Input:
iris_2d = np.genfromtxt('iris.data', delimiter=',', dtype='float', usecols=[0,1,2,3])

In [244]:
np.random.seed(100)
iris_2d = np.genfromtxt('iris.data', delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
proper_rows = iris_2d[np.sum(np.isnan(iris_2d), axis=1)==0]
proper_rows[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

### Q46. Find the correlation between SepalLength(1st column) and PetalLength(3rd column) in iris_2d
Input:
iris_2d = np.genfromtxt('iris.data', delimiter=',', dtype='float', usecols=[0,1,2,3])

In [246]:
iris_2d = np.genfromtxt('iris.data', delimiter=',', dtype='float', usecols=[0,1,2,3])
np.corrcoef(iris_2d[:,0],iris_2d[:,2])[0,1]

0.8717541573048714

### Q47. Find out if iris_2d has any missing values.
Input:
iris_2d = np.genfromtxt('iris.data', delimiter=',', dtype='float', usecols=[0,1,2,3])

In [247]:
iris_2d = np.genfromtxt('iris.data', delimiter=',', dtype='float', usecols=[0,1,2,3])
np.isnan(iris_2d).any()

False

### Q48. Replace all ocurrences of nan with 0 in numpy array
Input:
iris_2d = np.genfromtxt('iris.data', delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

In [249]:
iris_2d = np.genfromtxt('iris.data', delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
np.where((np.isnan(iris_2d)), 0, iris_2d)[:5]   # first 5 rows

array([[0. , 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

### Q49. Find the unique values and the count of unique values in iris's species
Input:
iris = np.genfromtxt('iris.data', delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [257]:
iris = np.genfromtxt('iris.data', delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
np.unique(iris[:,4], return_counts=True)

(array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
       dtype=object),
 array([50, 50, 50], dtype=int64))

### Q50. Randomly sample iris's species such that setose is twice the number of versicolor and virginica (keep the text column intact)
Input:
iris = np.genfromtxt('iris.data', delimiter=',', dtype='object')

In [277]:
np.random.seed(100)
iris = np.genfromtxt('iris.data', delimiter=',', dtype='object')
species_names = np.unique(iris[:,4])
result = np.random.choice(species_names, size=150, p=[0.5,0.25,0.25])
result[:50]

array([b'Iris-versicolor', b'Iris-setosa', b'Iris-setosa',
       b'Iris-virginica', b'Iris-setosa', b'Iris-setosa',
       b'Iris-versicolor', b'Iris-virginica', b'Iris-setosa',
       b'Iris-versicolor', b'Iris-virginica', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-virginica',
       b'Iris-virginica', b'Iris-setosa', b'Iris-virginica',
       b'Iris-setosa', b'Iris-setosa', b'Iris-virginica',
       b'Iris-virginica', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-virginica', b'Iris-setosa',
       b'Iris-versicolor', b'Iris-versicolor', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-virginica',
       b'Iris-virginica', b'Iris-setosa', b'Iris-virginica',
       b'Iris-versicolor', b'Iris-versicolor', b'Iris-versicolor',
       b'Iris-versicolor', b'Iris-setosa', b'Iris-setosa',
       b'Iris-versicolor', b'Iris-virginica', b'Iris-setosa',
       b'Iris-setosa', b'Iris-virginica'], dtype