# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [2]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [3]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [4]:
np.arange(10,50).shape

(40,)

5. Print the type of the previous array in question 3

In [5]:
np.arange(10,50).dtype

dtype('int32')

6. Print the numpy version and the configuration


In [6]:
print(np.__version__)
print(np.show_config())

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/awon/miniconda3/envs/q2\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/awon/miniconda3/envs/q2\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/awon/miniconda3/envs/q2\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/awon/miniconda3/envs/q2\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/awon/miniconda3/envs/q2\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/awon/miniconda3/envs/q2\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/awon/miniconda3/envs/q2\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/awon/miniconda3/envs/q2\\

7. Print the dimension of the array in question 3


In [7]:
np.arange(10,50).ndim

1

8. Create a boolean array with all the True values

In [8]:
boolean = np.ones(6, dtype=bool)
boolean

array([ True,  True,  True,  True,  True,  True])

9. Create a two dimensional array




In [9]:
x = np.arange(25).reshape(5,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

10. Create a three dimensional array



In [10]:
y = np.arange(30).reshape(2,3,5)
y

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [11]:
rev = np.arange(10).reshape(10,1)
np.flip(rev)

array([[9],
       [8],
       [7],
       [6],
       [5],
       [4],
       [3],
       [2],
       [1],
       [0]])

12. Create a null vector of size 10 but the fifth value which is 1 

In [12]:
x = np.zeros(10)
x[5]=1
x

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [13]:
y = np.identity(3, dtype='int')
y

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [14]:
arr = np.array([1, 2, 3, 4, 5])
arr.astype('float')

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [17]:
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
np.multiply(arr1,arr2)

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [3]:
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
np.equal(arr1,arr2)

array([[False, False, False],
       [False, False, False]])

17. Extract all odd numbers from arr with values(0-9)

In [6]:
x = np.arange(10)
x[x%2==1]

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [7]:
x[x%2==1]=-1
x

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [9]:
arr = np.arange(10)
arr[5:9]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [11]:
x = np.ones(25).reshape(5,5)
x[1:-1,1:-1]=0
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [12]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[1,1]=12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [14]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0,0]=64
arr3d

array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [16]:
x = np.arange(16).reshape(4,4)
y = x[0]
y

array([0, 1, 2, 3])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [2]:
x = np.arange(16).reshape(4,4)
y = x[1,1]
y

5

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [11]:
x = np.arange(10).reshape(2,5)
x[:2,2]

array([2, 7])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [28]:
y = np.random.randn(100).reshape(10,10)
np.min(y)
np.max(y)

2.6694177119749263

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [29]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [30]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [33]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
data[names!='Will']

array([[ 1.35350642,  1.16855618, -0.00914774,  2.03107293],
       [ 1.67451043, -0.79075251,  0.00627152,  0.24667811],
       [-0.28874489, -0.26648962, -0.37011942,  0.21367682],
       [ 0.20615397, -1.23993893,  0.6065001 , -0.33813483],
       [-0.96603383, -0.85405126, -0.24744607, -1.4241608 ]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [37]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
mask = (names != 'Will') & (names != 'Joe')
data[mask]

array([[ 2.96873996, -1.43009242,  1.56569655, -0.40457029],
       [ 1.28295707, -0.23632041, -1.25895831,  1.50888313]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [2]:
x = np.random.uniform(1,15, size=(5,3))
x

array([[ 5.78040543, 13.8358012 ,  6.59271304],
       [ 3.2583155 ,  9.48070714,  7.8168475 ],
       [13.30221587,  9.97170283,  1.61429968],
       [ 7.18840633,  8.11398993,  5.08980074],
       [ 8.19739214,  8.65456751,  4.78421729]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [9]:
y = np.random.uniform(1,16, size=(2,2,4))
y

array([[[15.42270704, 13.22691877,  6.30856294, 10.86978289],
        [12.49635064, 12.48867086, 13.07667916,  4.86191579]],

       [[15.54908955, 11.41288084,  5.28686249, 11.27564189],
        [14.62134094, 10.54417319,  1.48987232,  9.16769594]]])

33. Swap axes of the array you created in Question 32

In [16]:
y.swapaxes(1,2)

array([[[15.42270704, 12.49635064],
        [13.22691877, 12.48867086],
        [ 6.30856294, 13.07667916],
        [10.86978289,  4.86191579]],

       [[15.54908955, 14.62134094],
        [11.41288084, 10.54417319],
        [ 5.28686249,  1.48987232],
        [11.27564189,  9.16769594]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [28]:
arr = np.random.randn(10)*10
np.where(arr<0.5,0,(np.sqrt(arr)))

<ipython-input-28-88edc3488e2c>:2: RuntimeWarning: invalid value encountered in sqrt
  np.where(arr<0.5,0,(np.sqrt(arr)))


array([0.        , 0.        , 0.        , 3.89062781, 3.50722522,
       0.        , 2.24642239, 2.76768738, 3.1408616 , 0.        ])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [40]:
x = np.random.randn(12)
y = np.random.randn(12)
np.maximum(x,y)

array([ 0.52800452,  0.95631425,  0.16769359, -0.59466284, -0.10029036,
       -0.3471163 ,  0.44399563,  0.55326636,  0.89888975,  0.946148  ,
       -0.63019094,  1.12603695])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [41]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [42]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [44]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
sampleArray[1]=newColumn
sampleArray

array([[34, 43, 73],
       [10, 10, 10],
       [53, 94, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [45]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [47]:
x = np.random.random(20)
np.cumsum(x)

array([ 0.85078532,  1.14204854,  2.0285033 ,  2.16138193,  3.13650955,
        3.81500791,  4.6480879 ,  5.61081779,  6.10432017,  6.92810549,
        7.83317524,  7.97252097,  8.85290527,  9.69494433,  9.84106551,
       10.07959377, 10.21702936, 10.54868218, 11.36842655, 11.84335526])